### ISSUE TITLE
Formatted output with indents?

### ISSUE THREAD

**Issue by vatosarmat** [inspect-js/object-inspect#27]
Hello. Currently object-inspect always represents object as single line.

`{ a: 1, b: [ 3, 4, undefined, null ], c: undefined, d: null, e: { regex: /^x/i, buf: <Buffer 61 62 63>, holes: [ 'a', 'b', , , 'e', , 'g' ] }, now: Thu Nov 14 2019 20:59:42 GMT+1000 (Vladivostok Standard Time), self: [Circular] }`

How about adding the ability to produce formatted output?

```js
{
  a: 1,
  b: [ 3, 4, undefined, null ],
  c: undefined,
  d: null,
  e: {
    regex: /^x/i,
    buf: <Buffer 61 62 63>,
    holes: [ 'a', 'b', <2 empty items>, 'e', <1 empty item>, 'g' ]
  },
  now: 2019-11-14T10:59:42.159Z,
  self: [Circular]
}
```

**Comment by ljharb** [comment]
See #13
