### ISSUE TITLE
Remove dependency to node builtins

### ISSUE THREAD

**Issue by PFight** [inspect-js/object-inspect#38]
Using your package I receive troubles:

Rollup: "Creating a browser bundle that depends on Node.js built-in module ('util'). You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills"

Reason is that you require `util` package in `util.inspect.js` file. 

It is not good to depend on node builtins, so it would be better to remove `util` dependecy.

**Comment by ljharb** [comment]
The browser field ensures that the node core module is not used in a bundle. Rollup perhaps has a bug in its browser field implementation.

Separately, a non-broken node module bundler must polyfill node builtins. They will never be removed.
