### ISSUE TITLE
ReferenceError trying to access "global"

### ISSUE THREAD

**Issue by imirkin** [inspect-js/object-inspect#43]
When this runs in a browser (e.g. chrome):

    if (obj === global) {
        return '{ [object globalThis] }';
    }

we get a `ReferenceError`. Should that be `globalThis` instead? And/or should there be a check for global to be available (e.g. `typeof global !== "undefined"`)?

**Comment by ljharb** [comment]
No, it shouldn’t. This is a bug in your bundler - a working node module bundler should automatically handle node globals, including `global`. Since this is a node module, these things are always required to be available.

**Comment by imirkin** [comment]
This is an Angular application, using angular-cli's invocation of webpack as the bundler. No "node" involved - the whole reason for using this library is because there's no util.inspect from node...

Didn't realize that this was targeted at node only... it worked great until now :(

**Comment by ljharb** [comment]
Every non module is a node module - that doesn’t mean it’s targeted at node only, but it does mean a working node module bundler is required.

If angular cli has updated to use webpack 5, which breaks node module bundling by default, then I’d suggest filing an issue with angular cli to fix their webpack config.

**Comment by imirkin** [comment]
Angular CLI does indeed use webpack 5 (at least with Angular 16 - perhaps earlier too). Never ran into this type of issues before.

I guess your expectation is that something like browserify is used to bundle this package -- but that's specifically a "make browser env look like node env" tool (e.g. https://github.com/browserify/browserify-handbook?tab=readme-ov-file#global). An npm package may be targeted directly at browsers, as this one worked just fine before without any node-specific dependencies.

I think for now, I'll just keep object-inspect set to 0.12.3.

Thanks for your responses!

**Comment by ljharb** [comment]
This isn’t a recent change here - it's a result of webpack 5 being broken, and angular cli failing to compensate for that.

**Comment by imirkin** [comment]
It's a result of this change: https://github.com/inspect-js/object-inspect/commit/431bab21a490ee51d35395966a504501e8c685da

**Comment by ljharb** [comment]
Fair. It’s still due to webpack 5 being broken. Please file an issue with angular cli.

**Comment by imirkin** [comment]
I would, but I don't really have enough context to do so. I've tried in the past with issues where I'm a bit out of my depth, and it has been a waste of my time, largely put in by shuttling information between the two warring projects.

What webpack is doing sounds reasonable to me -- I don't really see a linkage between npm (file delivery / dependency management) and node, so assuming that code is node-specific seems a bit off to me (e.g. imagine an npm package of jquery). You're making the assertion that it's wrong, and it sounds like you know a lot more about it than I do, so I'm happy to go with your assessment. Perhaps a disagreement between you and the webpack authors though, otherwise by the 89th revision of webpack 5 they would have sorted it out? I haven't seen any mention of this in the Angular info either, so either they're keeping mum on this issue that tons of people are running into using angular-cli, or the problem is restricted to a handful of projects that people just avoid using since they "don't work". Some unofficial guides just recommend globally doing `window.global = window`, which I suppose is pragmatic.

Either way, I'm just trying to have code run, so locking a version of your highly useful package (thanks!) seems like the simplest way to go - the functionality introduced in 0.13 aren't "killer" for me, we just use this for some debug logging to the server.

**Comment by joshuahhh** [comment]
It appears that `global` is deprecated in Node (as well as being unsupported in browser environments): https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#global.

Would replacing this use of `global` with the universally-supported `globalThis` resolve this issue and make everyone happy? (The subtleties of global contexts escape me, so it's possible the answer is "no".)

Thanks. :)

**Comment by ljharb** [comment]
“Legacy” is not “deprecated”, and it’s never going away.

globalThis isn’t universally available in the node and browser versions this package supports, so it’s not an option.

A node module bundler that doesn’t automatically handle `global` is broken, full stop.

**Comment by jaclas** [comment]
I have exactly the same problem with an application created in SvelteKit.

**Comment by imirkin** [comment]
To get people going, you can just do

```
    "object-inspect": "1.12.3",
```

in your `package.json`'s dependencies. You'll miss out any improvements to this package, but assuming you're happy with that version's functionality, it shouldn't cause any real problems.

Perhaps at some point in the future, this package will stop requiring a node execution environment, or another package will emerge which supports browser environments without jumping through hoops. But I'm happy with the functionality of that version, so I don't feel the need to invest the effort there.
